services:
  qlawkus:
    build:
      dockerfile: docker/Dockerfile.jvm
    environment:
      QUARKUS_PROFILE: dev
      JAVA_OPTS_APPEND: >-
        -Dquarkus.http.host=0.0.0.0
        -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
