tts-1:
  pt_br:
    model: voices/pt_BR-cadu-medium.onnx
    speaker:
  en_ryan:
    model: voices/en_US-ryan-high.onnx
    speaker:
tts-1-hd:
  pt_br:
    model: voices/pt_BR-cadu-medium.onnx
    speaker:
  en_ryan:
    model: voices/en_US-ryan-high.onnx
    speaker:
