quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.qlawkus=qlawkus-test
quarkus.security.users.embedded.roles.qlawkus=admin
quarkus.http.auth.basic=true

%test.qlawkus.startup-thought.enabled=false
%test.quarkus.hibernate-orm.schema-management.strategy=validate
%test.quarkus.flyway.clean-at-start=true
%test.quarkus.langchain4j.ollama."ollama-fallback".base-url=http://localhost:11434
%test.quarkus.langchain4j.openai."nvidia".timeout=120s
