ALTER TABLE skill ADD COLUMN last_used_at TIMESTAMP;
ALTER TABLE skill ADD COLUMN use_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE skill ADD COLUMN state VARCHAR(16) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE skill ADD COLUMN pinned BOOLEAN NOT NULL DEFAULT false;
