Args = --initialize-at-run-time=com.sun.jna.Native \
  --initialize-at-run-time=com.sun.jna.Structure \
  --initialize-at-run-time=com.sun.jna.platform.win32.Kernel32 \
  --initialize-at-run-time=com.sun.jna.platform.win32.Kernel32Util \
  --initialize-at-run-time=com.sun.jna.platform.win32.Version \
  --initialize-at-run-time=com.sun.jna.platform.win32.Advapi32 \
  --initialize-at-run-time=com.sun.jna.platform.win32.Advapi32Util \
  --initialize-at-run-time=com.sun.jna.platform.win32.Crypt32 \
  --initialize-at-run-time=com.sun.jna.platform.win32.Crypt32Util \
  --initialize-at-run-time=com.sun.jna.platform.win32.NtDll \
  --initialize-at-run-time=com.sun.jna.platform.win32.Ole32 \
  --initialize-at-run-time=com.sun.jna.platform.win32.OleAuto \
  --initialize-at-run-time=com.sun.jna.platform.win32.Ddeml \
  --initialize-at-run-time=com.sun.jna.platform.win32.DdemlUtil \
  --initialize-at-run-time=com.sun.jna.platform.win32.Mpr \
  --initialize-at-run-time=com.sun.jna.platform.win32.PowrProf \
  --initialize-at-run-time=com.sun.jna.platform.win32.Psapi \
  --initialize-at-run-time=com.sun.jna.platform.win32.Shell32 \
  --initialize-at-run-time=com.sun.jna.platform.win32.Shell32Util \
  --initialize-at-run-time=com.sun.jna.platform.win32.User32 \
  --initialize-at-run-time=com.sun.jna.platform.win32.User32Util \
  --initialize-at-run-time=com.sun.jna.platform.win32.W32ServiceManager \
  --initialize-at-run-time=com.pty4j.windows.WinPtyProcess \
  --initialize-at-run-time=com.pty4j.windows.winpty.WinPty \
  --initialize-at-run-time=com.pty4j.windows.winpty.WinPtyLibrary
